version: '1.0'
services:
  server:
    build:
      context: ./ecommerce-go-server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on: 
      - db
    env_file:
      - ecommerce-go-server/.env
      - ecommerce-go-server/development.env
      - ecommerce-go-server/production.env
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecurepassword
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_USER=nicolas
      - MYSQL_PASSWORD=mysecurepassword
    
    ports:
      - 3307:3306
    volumes:
      - ./dbdata:/var/lib/mysql
  client:
    build:
      context: ./ecommerce-next-js-client
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - server
volumes:
  dbdata: