version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    labels:
      - "traefik.http.routers.ecommerce-server.rule=Host(`server-ecommerce-x.alligatorcode.pro/api`)"
      - "traefik.http.routers.ecommerce-server.entrypoints=websecure"
      - "traefik.http.routers.ecommerce-server.tls.certresolver=myresolver"
    depends_on: 
      db:
        condition: service_healthy
    networks:
      - traefik_main_network
    env_file:
      - server/.env
      - server/production.env

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecurepassword
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_USER=nicolas
      - MYSQL_PASSWORD=mysecurepassword
    volumes:
      - ./dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    labels:
      - "traefik.http.routers.ecommerce-client.rule=Host(`ecommerce-x.alligatorcode.pro`)"
      - "traefik.http.routers.ecommerce-client.entrypoints=websecure"
      - "traefik.http.routers.ecommerce-client.tls.certresolver=myresolver"
    depends_on:
      - server
    networks:
      - traefik_main_network

volumes:
  dbdata:

networks:
  traefik_main_network:
    external: true

# version: "3"
# services:
#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile.prod
#     ports:
#       - 8081:8080
#     depends_on: 
#       db:
#         condition: service_healthy
#     env_file:
#       - server/.env
#       - server/production.env
#       # - server/development.env
#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       - MYSQL_ROOT_PASSWORD=mysecurepassword
#       - MYSQL_DATABASE=ecommerce_db
#       - MYSQL_USER=nicolas
#       - MYSQL_PASSWORD=mysecurepassword
#     ports:
#       - 3307:3306
#     volumes:
#       - ./dbdata:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10
#   client:
#     build:
#       context: ./client
#       dockerfile: Dockerfile.prod
#     ports:
#       - 3001:3000
#     depends_on:
#       - server
# volumes:
#   dbdata: