-- the following will insert dog food into our mysql database

insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Curry Paste - Green Masala', 'transition innovative channels', 66.22, 8, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Bread - 10 Grain Parisian', 'synergize one-to-one communities', 35.75, 9, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Garbage Bags - Clear', 'orchestrate bricks-and-clicks deliverables', 38.94, 3, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Bread - Flat Bread', 'reintermediate B2B functionalities', 62.19, 1, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Monkfish - Fresh', 'synergize cross-platform metrics', 36.41, 2, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Oven Mitts - 15 Inch', 'architect one-to-one infrastructures', 81.06, 9, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Jack Daniels', 'deliver next-generation deliverables', 36.35, 5, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cake - Bande Of Fruit', 'utilize global web services', 69.16, 5, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Radish - Black, Winter, Organic', 'implement scalable e-markets', 78.31, 5, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Radish', 'monetize revolutionary e-tailers', 75.14, 9, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Bread - Dark Rye, Loaf', 'scale extensible mindshare', 93.98, 2, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Sauce - White, Mix', 'grow holistic platforms', 84.27, 7, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Flour - Semolina', 'engage best-of-breed deliverables', 67.11, 8, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Yokaline', 'innovate visionary web-readiness', 31.29, 2, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Sauce - Caesar Dressing', 'extend robust infrastructures', 10.7, 3, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Tia Maria', 'revolutionize intuitive networks', 89.77, 6, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('V8 Pet', 'target strategic e-services', 32.35, 1, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pork - Smoked Back Bacon', 'productize leading-edge web services', 48.35, 6, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Syrup - Monin - Granny Smith', 'aggregate leading-edge e-markets', 32.24, 8, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Papayas', 'reinvent killer systems', 95.16, 7, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Sugar - Crumb', 'harness user-centric relationships', 13.43, 6, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cookie Trail Mix', 'integrate mission-critical web-readiness', 61.24, 2, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Juice - Cranberry 284ml', 'facilitate e-business partnerships', 75.22, 3, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cookie Trail Mix', 'monetize virtual web services', 52.83, 6, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pie Filling - Apple', 'productize innovative infrastructures', 32.61, 4, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Squash - Acorn', 'engineer world-class architectures', 84.48, 2, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Water - Spring Water 500ml', 'grow open-source applications', 60.04, 9, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pork - European Side Bacon', 'architect proactive e-tailers', 39.66, 3, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cheese Cloth', 'repurpose innovative initiatives', 62.64, 4, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Versatainer Nc - 888', 'orchestrate synergistic functionalities', 39.34, 7, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Wine - White, Mosel Gold', 'utilize global niches', 28.84, 7, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Tea - Vanilla Chai', 'scale wireless bandwidth', 32.32, 1, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Lettuce - Boston Bib', 'implement visionary mindshare', 17.5, 5, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Lamb Tenderloin Nz Fr', 'leverage enterprise solutions', 15.75, 5, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Vanilla Beans', 'optimize enterprise web services', 53.95, 8, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Ginger - Crystalized', 'generate dot-com bandwidth', 70.35, 4, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Quail - Whole, Bone - In', 'strategize e-business niches', 72.99, 2, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pineapple - Regular', 'recontextualize synergistic functionalities', 28.58, 5, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Chicken - Bones', 'redefine one-to-one deliverables', 90.98, 9, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Veal - Brisket, Provimi,bnls', 'embrace bleeding-edge eyeballs', 88.24, 1, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Ginger - Pickled', 'streamline viral solutions', 45.77, 8, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Puff Pastry - Sheets', 'syndicate viral methodologies', 14.18, 1, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Jerusalem Artichoke', 'monetize world-class e-markets', 9.02, 7, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Tea - Orange Pekoe', 'scale world-class deliverables', 65.32, 6, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Langers - Mango Nectar', 'transition enterprise metrics', 80.72, 8, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pepperoni Slices', 'optimize web-enabled e-markets', 23.05, 7, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Beef - Texas Style Burger', 'disintermediate impactful content', 82.31, 8, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Steel Wool', 'visualize user-centric content', 39.42, 8, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cake - French Pear Tart', 'grow web-enabled solutions', 94.73, 4, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Chips Potato Salt Vinegar 43g', 'architect cross-platform content', 49.37, 3, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Bread Base - Goodhearth', 'facilitate magnetic networks', 25.88, 9, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Muffin Mix - Morning Glory', 'empower dynamic channels', 15.62, 4, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Sambuca - Opal Nera', 'e-enable front-end metrics', 55.04, 6, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Soup - French Onion, Dry', 'engage holistic systems', 53.31, 1, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Table Cloth 53x69 White', 'incentivize virtual interfaces', 21.19, 4, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Tuna - Salad Premix', 'transform seamless solutions', 46.69, 8, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Brandy - Bar', 'transform bleeding-edge portals', 18.88, 4, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Wine - Sake', 'strategize viral vortals', 16.1, 5, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pork Ham Prager', 'whiteboard distributed markets', 75.56, 5, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pork - Sausage, Medium', 'integrate next-generation e-markets', 44.25, 6, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Muffin Batt - Choc Chk', 'matrix end-to-end interfaces', 58.16, 6, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Beef - Top Sirloin - Aaa', 'utilize integrated bandwidth', 60.73, 8, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Wine - Blue Nun Qualitatswein', 'deliver clicks-and-mortar e-services', 20.92, 8, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Tandoori Curry Paste', 'deploy innovative architectures', 24.33, 3, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Turkey Tenderloin Frozen', 'revolutionize distributed deliverables', 60.45, 2, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Island Oasis - Magarita Mix', 'deploy extensible channels', 84.52, 1, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Peppercorns - Green', 'transition transparent functionalities', 72.76, 6, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pork - Ground', 'synergize one-to-one users', 93.7, 5, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Vinegar - Raspberry', 'drive granular methodologies', 15.98, 9, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Creme De Menth - White', 'utilize proactive portals', 99.69, 4, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Beans - Black Bean, Canned', 'empower transparent infomediaries', 38.05, 1, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cheese - Oka', 'mesh value-added e-services', 75.46, 1, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Amarula Cream', 'reintermediate strategic bandwidth', 6.28, 7, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Sprouts - Bean', 'whiteboard dot-com communities', 79.69, 1, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cheese - Manchego, Spanish', 'optimize ubiquitous applications', 17.19, 2, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Sterno - Chafing Dish Fuel', 'deploy value-added applications', 52.0, 4, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Potatoes - Purple, Organic', 'expedite killer schemas', 51.17, 6, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pomello', 'iterate value-added functionalities', 41.99, 2, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Sambuca - Opal Nera', 'innovate seamless metrics', 57.97, 2, 5);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Kolrabi', 'implement innovative synergies', 70.44, 8, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Cheese - Cottage Cheese', 'expedite bricks-and-clicks markets', 38.61, 1, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Pasta - Lasagna, Dry', 'deploy plug-and-play synergies', 12.23, 8, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Beef - Short Ribs', 'e-enable synergistic synergies', 50.35, 3, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Veal - Leg', 'benchmark sticky niches', 62.55, 3, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Veal - Slab Bacon', 'orchestrate proactive models', 93.07, 8, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Jameson Irish Whiskey', 'grow vertical e-business', 96.9, 7, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Bacardi Limon', 'streamline robust metrics', 76.89, 6, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Soup - Campbells, Spinach Crm', 'whiteboard global relationships', 30.09, 5, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Ham - Proscuitto', 'deploy visionary markets', 55.93, 7, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Squid - U 5', 'cultivate synergistic portals', 93.18, 7, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Soupfoamcont12oz 112con', 'integrate front-end supply-chains', 48.84, 5, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Parsley Italian - Fresh', 'redefine next-generation communities', 83.35, 3, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Muffin - Mix - Strawberry Rhubarb', 'mesh transparent architectures', 60.87, 6, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Beer - Maudite', 'incentivize leading-edge methodologies', 97.86, 4, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Marjoram - Dried, Rubbed', 'synthesize killer models', 62.59, 4, 1);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Tandoori Curry Paste', 'enable visionary metrics', 10.47, 8, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Noodles - Cellophane, Thin', 'brand B2C portals', 47.53, 2, 3);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Ecolab - Orange Frc, Cleaner', 'incentivize 24/365 web services', 28.87, 4, 4);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Wine - Ej Gallo Sierra Valley', 'target innovative paradigms', 23.49, 1, 2);
insert into ecommerce_db.products (name, description, price, product_category_id, product_pet_type_id) values ('Waffle Stix', 'cultivate ubiquitous web services', 96.5, 5, 1);

SELECT * FROM ecommerce_db.products;


